### ISSUE TITLE
Email notification upon new discussion

### ISSUE THREAD

**Issue by rlogiacco** [gwillem/freeflarum.com#1]
I kindly request to add the flagrow/subscribed extension to FreeFlarum so that I can get a notification by email whenever a new discussion is created on the freeflarum forum I administer.

I know you are on hold until beta-8 is released (which I hope occurs sooner than later).

**Comment by gwillem** [comment]
I like this extension, however as this will generate a lot of mails, I fear that my quotum at Mailgun will deplete quickly. So gotta think of a solution for that first.

**Comment by xCustomWorld** [comment]
**Alternative solution:**
The `reFlar/webhook` extension might do the trick for those who has Discord or Slack.
The setup is quite simple and you will recieve notifications about what you want instantly, right to one of your Discord or Slack channels. Perfect solution for those who want to be notified about every single step at their forum ._. :)

**Comment by xCustomWorld** [comment]
I decided to change the title due to people requesting extensions like this. Keep in mind that we _currently_ do not support extensions that generate a lot of mails. Our mail's hosting quota is limited and FreeFlarum is free service. We are, however, trying our best to think of an other alternative solutions. 

My webhooks solution above is perhaps not exactly what you currently need, but it's currently the closest solution possible when it comes to notifying users of new discussions. I will perhaps make a documentation about the webhooks too, so you can go on and try it yourself ;)

**Comment by brechtm** [comment]
I learned that there are several mail service provides that offer generous free plans: [Recommended Email Providers for Discourse](https://github.com/discourse/discourse/blob/master/docs/INSTALL-email.md). You could consider requiring all forums to configure their own email service so that there's never an issue with your mail hosting quota. This wouldn't require any extension-specific checks. The disadvantage would of course be that this is much less user-friendly. However, setting up a custom email server should be fairly simple with a step-by-step guide.

**Comment by ben-qnimble** [comment]
+1 for adding the subscribed plugin. I wonder if it would be possible to restrict this plugin to forum's that are configured to use an external smtp provider, so this would avoid the email / spam issues.  Or requiring an external mail service for sending any mails would be fine with me (but I can appreciate it adds more steps to people who just want a simple forum to work out of the box).
