### ISSUE TITLE
An error occurred while trying to load this page

### ISSUE THREAD

**Issue by ghiathkamel** [gwillem/freeflarum.com#126]
Hello, i get this message :
An error occurred while trying to load this page
https://forum.wrdo.org/auth/twitter
what can i do to fix it
Thanks

**Comment by CWKevo** [comment]
The auth pages cannot load, they're supposed to be functional and have data flow through them (such as login info). In this case, you're loading the page on your own, with no data specified so an error occured. That's okay, because the data comes as long as you login by social media by using the button(s) for that in the login/register popup at your forum. In other words, that page does not really have to bother you.

You have to go into incognito mode and login by using social media at your forum from there in order to find out if the logins on your forum work properly. Incognito mode makes sure that no cookies or sessions get saved, so in case it doesn't work, you can try again by simply re-openning the incognito (or you can try different browser) or just logging out, so you don't interfere with your main login. If it isn't working, try to follow the external error message from the social media (if there's any, in most cases it's invaid redirect URI, etc...).

**Comment by ghiathkamel** [comment]
i tried incognito mode many times but no luck yet
is there a tutorial how to setup this /auth/twitter at freeflarum
Thanks

**Comment by CWKevo** [comment]
No there is unfortunately no info for setting up Twitter auth (did we miss that?). If you give me ~2 days, I can add it to the documentation.

**Comment by ghiathkamel** [comment]
![Annotation 2020-07-31 192514](https://user-images.githubusercontent.com/60829719/89087913-e4149a80-d363-11ea-9249-07aa007b07a7.png)

**Comment by ghiathkamel** [comment]
take your time
all working good , only twitter not working

**Comment by ghiathkamel** [comment]
Thanks to GOD, now it works

**Comment by ghiathkamel** [comment]
https://discuss.flarum.org/d/21470-twitter-login-extension-how-to-create-an-twitter-app
