### ISSUE TITLE
-Question-About cloudflare

### ISSUE THREAD

**Issue by sysdl132** [gwillem/freeflarum.com#127]
__Your question:__
If I add my freeflarum domain(sl132.flarum.cloud) to cloudflare account,what will happen?
Can you help me to test that?Or give me a guide?  :)

**Comment by CWKevo** [comment]
I have checked [this](https://support.cloudflare.com/hc/en-us/articles/201720164-Creating-a-Cloudflare-account-and-adding-a-website/) by Cloudflare. I have personally never used Cloudflare, but they mention to add a root domain. Root domain is `flarum.cloud` or `freeflarum.com` in FreeFlarum's case, so that won't work as FreeFlarum uses subdomains.

I don't know if it's required to add a site to Cloudflare, but if it's optional, then I would just ignore it. If you are trying to add a custom domain to your forum, please check [this](https://www.freeflarum.com/docs/how-to/advanced-setup/custom-domain/) guide.

**Comment by sysdl132** [comment]
Thanks

**Comment by CWKevo** [comment]
Glad you solved this... If you have any other questions, don't hesitate to ask.
