### ISSUE TITLE
Reply Button not scrolling down when click on it

### ISSUE THREAD

**Issue by ghiathkamel** [gwillem/freeflarum.com#133]
Hello everyone,
When i click on the reply blue button the page scroll down to the reply box this is good, but when clicking on the reply text button the page not scroll down, how can I fix this, please take a look: https://www.wrdo.org/contact 
Thanks

**Comment by ghiathkamel** [comment]
This is bug on chrome and edge but not on the firefox browser?
this is important how can i fix this  
Thanks

**Comment by CWKevo** [comment]
This bug can be caused by my code as I said in #131, hence the reference.

You should try if it works normally without my code. You can just paste it in Notepad or some text file and then after you're done testing, you can paste it back, depending on if it'll work normally with no code (if yes, then my code breaks it).

It could also be that you pasted the code wrongly and maybe there is a syntax error. Could you please paste what code do you have in your header?

**Comment by ghiathkamel** [comment]
the issue only in the embed box , not in the forum , i removed all the codes in the header , and the issue still there
in firefox there is no issue at all ,

**Comment by CWKevo** [comment]
This means that the Embed extension somewhat breaks that feature in Chrome or other browsers. The Flarum Embed repository does not allow opening issues, so you could try and ask on discuss about this issue. It could be an issue with the extension, but also with your site. Unfortunately, we cannot fix these bugs and you're pretty much on your own. Sorry.

I will try to create an embed discussion on a blank site and if the problem still occurs, it is a bug in the extension.

**Comment by ghiathkamel** [comment]
Thank you my friend, Please let me know if you still have same issue, yes i think its bug in the extension, not at freeflarum, i will ask at flarum too

**Comment by CWKevo** [comment]
This is strange. I set up a blank site and tried embedding both your discussion at your forum and my discussion at mine forum using the same iFrame code.

When I embed your discussion, it throwed an error when I tried to log in to the forum from the embed.

But when I embed my discussion, it worked perfectly and I could log into my forum with no problem and reply to it. It didn't scroll down, but it opened post composer below so that shouldn't be a big problem.

I guess it isn't a bug in the extension, but something's wrong at your forum or possibly the site you put the embed in. I'll check it.

**Comment by ghiathkamel** [comment]
> It didn't scroll down, but it opened post composer below so that shouldn't be a big problem.

Thanks for trying, because I am using large size of embed box, i need to scroll down to see the post composer :(

**Comment by CWKevo** [comment]
When you click on the reply in post actions the composer stays fixed on the bottom of the page, you don't need to scroll down (at least not for me).

**Comment by ghiathkamel** [comment]
this is strange, I need to scroll down only on edge and chrome not in firefox, the good news is i opened this link in my browser to test the extension and it works perfectly in all browsers:
https://forum.wrdo.org/embed/2-chat
but with embed style because its big embed box size i need to scroll down:
https://www.wrdo.org/contact
but in  firefox works perfectly , 
i will close this here, and i will open this in https://discuss.flarum.org/
Thank you for your time
