### ISSUE TITLE
Extensions Break Website

### ISSUE THREAD

**Issue by melonpocky** [gwillem/freeflarum.com#150]
Hi, 

I am new to forum engines, so please bear with me. I am trying to develop a community forum only for the website to break when I add extensions. What am I able to do to remediate this? Thank you.

**Comment by CWKevo** [comment]
What extensions did you enable when the forum broke? Could you share your FreeFlarum forum name with us so we can take a look?

**Comment by CWKevo** [comment]
I have found out that if you enable the "Discussion Templates" extension when "Tags" is not enabled, it bricks your forum Administration panel.

In case of another extension however, more details are needed. For now, if you tell us your forum name, we can unblock it.

**Comment by melonpocky** [comment]
Thank you for responding quickly! I had to delete my site since the default post "Things that you can do with Flarum" had my email address available for everyone to see. Since I was unable to access my admin page, I deleted the forum and started a new one. 

I was enabling multiple extensions but from what you've stated, that was the problem I was having. I remembered that I enabled "Discussion Templates" and didn't enable "Tags".

**Comment by CWKevo** [comment]
I have reported the error to the extension developer, so I'm waiting for a fix. It is always recommend to experiment on an experimental forum. Flarum is in beta, and you have to be careful with extensions because sometimes even loading/enabling order matters - if you enable "Discussion Templates" without reloading page and then enabling "Tags", your forum will still get an error because "Discusion Templates" was enabled first, so it also loads first before "Tags" (which wasn't enabled yet, but when you enable it, it's late).

I went on my test forum and enabled all extensions and I have found out that "Doorman" breaks with Czech language because the Czech locale file has invalid encoding. I have reported this as well and patched it for FF. Keep an eye open for more bugs and report any findings so we can possibly fix it :)

About the E-Mail showing, I understand that it might be kind of an issue, maybe we should just put "Your login details were sent to your E-mail address." without actually putting the address.
