### ISSUE TITLE
Extension Request - Best Answer by WIWATSRT & upload by flagrow

### ISSUE THREAD

**Issue by niteshmanav** [gwillem/freeflarum.com#17]
Kindly add this extension called "Best Answer by WIWATSRT" and "upload by flagrow"

Here is the link - https://flagrow.io/extensions/wiwatsrt/flarum-ext-best-answer

https://flagrow.io/extensions/flagrow/upload

These are top two extensions on the list at https://flagrow.io/ , amazed to find that it's not already included. 

Thank you.

**Comment by xCustomWorld** [comment]
Sadly, FreeFlarum does not support any extension that allows file uploads or run of PHP code. It is because someone could upload harmful files to infect our interface and possibly run other forums in danger. 

As an alternative for image uploads and GIFs, we already have the [Imgur Upload](https://github.com/matteocontrini/flarum-imgur-upload) extension installed, so be sure to check it out. 

For other file uploads, I would recommend:

1. Finding extension like the Imgur one - extension that uploads the file to third-party services and then inserts link to the file into the post.
2. Upload it to third-party services by yourself and share a link to the file.

As for "Best Answer", we'll see when @gwillem looks into this.

**Comment by gwillem** [comment]
Thanks for your request. However, both extension are currently incompatible with the FreeFlarum platform, so I cannot install them.

**Comment by xCustomWorld** [comment]
The (best answer)[https://discuss.flarum.org/d/3868-select-post-best-answer] extension is now compatible with beta.10

![image](https://user-images.githubusercontent.com/39010496/65767332-dc75db00-e12d-11e9-89c3-425f5313992a.png)
