### ISSUE TITLE
Brazilian Portuguese Language Pack

### ISSUE THREAD

**Issue by mpotto** [gwillem/freeflarum.com#176]
__Packagist URL for extension:__
https://packagist.org/packages/tiu-ram0n/brazilian-portuguese

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

Discussion is active and current on the [Flarum Community](https://discuss.flarum.org/d/18543-language-pack-portuguese-brazilian) and the package is listed as "Compatible with Flarum 0.1.0-beta.15" on [Extiverse](https://extiverse.com/extension/tiu-ram0n/brazilian-portuguese).

_This request needs at least 7 upvotes to be accepted._

**Comment by CWKevo** [comment]
Officially, the extension is not beta.15 yet and was removed due to the following error, which I reported: https://discuss.flarum.org/d/18543-language-pack-portuguese-brazilian/27

I have re-added it, but keep in mind that errors may occur. If it'll cause big problems, we'll have to remove it again.

**Comment by mpotto** [comment]
Ah, ok, thanks for adding it again -- accessibility is an important part of the forum I am building. I think I've skipped your error report on https://discuss.flarum.org/d/18543-language-pack-portuguese-brazilian/27, sorry.

If I find any problems, I'll report ASAP.
