### ISSUE TITLE
Error Code 500 on Refresh

### ISSUE THREAD

**Issue by Alexandre2006** [gwillem/freeflarum.com#207]
When you visit a post on my forum (https://thinkalex.flarum.cloud) and refresh the page, you will be told "An error occured while trying to load this page." I am using freeflarum and I'm not sure how to debug this error.

__My FreeFlarum forum URL:__  

https://thinkalex.flarum.cloud

**To Reproduce:**

1. Go to home page
2. Open first post
3. Refresh page

**Expected behavior:**

The forum behaves normally and the post is visible.

**Comment by CWKevo** [comment]
This only happens while accessing the blog page directly (e. g.: from the search bar) and is related to the SEO extension:

```
flarum.ERROR: Exception: V17Development\FlarumSeo\Extend::setTitle(..): Container was not yet initialized. in /app/vendor/v17development/flarum-seo/src/Extend.php:196
```

If I am not mistaken, this was fixed in beta.16 releases of the Blog extension. The only issue that holds us back from updating is that extend.php doesn't extend at our dev server. It is possible that it happens only at the dev server, but I guess we'll have to find out then. I think that we could update today, so I'm closing this

**Comment by Alexandre2006** [comment]
Thank you for your support. Do you mind telling me how I could find these logs?

**Comment by meetdilip** [comment]
I do not think normal users have access to the logs.

**Comment by CWKevo** [comment]
No, they don't, but I plan to implement a system for viewing the logs in the future
