### ISSUE TITLE
Writing problem on android smartphones

### ISSUE THREAD

**Issue by nousername-it** [gwillem/freeflarum.com#213]
Could it be fixed?

**Comment by CWKevo** [comment]
How are we supposed to be fixing anything when you do not provide us a single detail about the issue, how to reproduce it, what happens and what you expect to happen? Please, be more specific about the issue that you are having

I think that you are talking about typing delay errors. This is an error in the markdown plugin that Flarum is using and cannot be fixed by us (although a temporary fix is available until it gets fixed in the next release https://discuss.flarum.org/d/26851)

**Comment by meetdilip** [comment]
It would be nice to know 

1. Android device model
2. Android version
3. Browser in question
4.  Browser version
5. If possible, a screen capture of this particular error.

**Comment by nousername-it** [comment]
> 5\. le, a screen capture of this particular error.

It happens on my Huawei Psmart Z Android 10.0.0.0 it occurs on Chrome, Opera, and Firefox . The worst is on HUAWEI browser when it force the user to write in CAPLOCK https://youtu.be/nNCgIJ_Aoxs this just emphasizes the same problem on other browsers https://youtu.be/wtRfcRBU2EI
Also it prompts this annoying "You don't have the permission to do this stuff" even if the user has the permissions to reply.

**Comment by CWKevo** [comment]
What's your forum name and what extensions did you enable when it started happening?

As FreeFlarum is just a Flarum hosting, we cannot fix issues related to Flarum or extensions. This seems like such issue, so it would be better to report this to https://discuss.flarum.org

**Comment by meetdilip** [comment]
Hi, I am able to write properly on my Android phone. As mentioned above you will get more Flarum related support at Discuss. 

You can also try disabling the extensions and try to pinpoint the error.
