### ISSUE TITLE
The requested resource was not found.

### ISSUE THREAD

**Issue by StudziakYT** [gwillem/freeflarum.com#230]
Hello, I have a problem with my forum, when I enter a thread it says "The requested resource was not found.
"also shows that there are 0 discussions and 0 posts. Can you restore some posts, at least Forum Rules?

Forum: https://forum.freshmc.pl

**Comment by CWKevo** [comment]
Please, follow the templates.

What did you do prior to when this happened (e. g.: did you enable an extension, etc...)? Are there any errors in the console? Do you moderate the forum alone? Are the permissions correctly set up in order to view the posts (if you're logged in as admin, you have all permissions, so check that too)

I can see that the discussion and post data is in your database, they just don't seem to be rendered in the actual forum.
