### ISSUE TITLE
Request problem (again)

### ISSUE THREAD

**Issue by StudziakYT** [gwillem/freeflarum.com#236]
__Describe the bug:__

I have the same error again that I can not see anything, from the moment the forum was available until then I set it up again, after doing all the categories etc. I wanted to finally add posts to tags and categories, but when I entered the discussions, again nothing there was when I re-entered via the link to the topic it showed that there is no such page. I am asking for help because now I have spent a lot of time doing it all and I am slowly falling from it. I would like to ask that everything really stay in its place because I don't want to do it again for so long <3

__My FreeFlarum forum URL:__

https://forum.freshmc.pl
**To Reproduce:**

1. Go to any topic in forum

**Expected behavior:**

**Screenshot(s) of the bug (optional):**

**Comment by CWKevo** [comment]
```
Column already exists: 1060 Duplicate column name 'created_at' (SQL: alter table `post_reactions` add `created_at` timestamp null, add `updated_at` timestamp null) in /app/vendor/illuminate/database/Connection.php:692
```

What extension(s) did you enable before the issue appears? I'm also seeing a warning that your E-mail settings are incorrect.

However, at this point I am concerned that the error might be related to our MySQL setup. I haven't heard that other forums would have this issue, but it's just that noone might've reported it. I will check some other forums & MySQL logs for errors too, just in case

**Comment by CWKevo** [comment]
Okay, I have found no errors except for the mail one. That made me think that Flarum just doesn't render the posts because of the tags, which you mentioned that you had recently worked with.

Indeed, disabling the tags & categories extension fixed the issue, and posts are shown normally now (and can also be created normally). This means that there is something wrong with the tags table. Shall I remove it? You will need to re-setup all tags, which I can do for you tomorrow if you want to

**Comment by StudziakYT** [comment]
Recently, I was actually firing all those that were marked on there. As for Tags and Categories, they can be removed and repaired, I care about ranks and other settings. Overall, I also had a problem with some plugins, e.g. reactions because they wouldn't turn on. There was an error popping up, I think it's also worth checking out. Thank you very much for your help, please let me know when it's fixed.

**Comment by CWKevo** [comment]
I saw database error for reactions too... Overall, it seems that (most of) your database is corrupt.

When I am at the discussion page, no server side error was logged. Flarum treated it as if the discussions did not exist and returned just a 404 client side. When I tried to post a discussion, a database error was finally triggered server-side. It was related to reactions, so I removed the reactions table. Now the error is:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum_freshmc.post_reactions' doesn't exist (SQL: alter table `post_reactions` add `created_at` timestamp null, add `updated_at` timestamp null) in /app/vendor/illuminate/database/Connection.php:692
```

...which makes sense - the table does not exist, and Flarum isn't recreating it. I will have to manually re-create it then.

My best guess is that the database got corrupt due to small database outage (e. g.: the database server was very busy, or was restarting at the moment). I personally do not like these kind of issues, but I will try my best to fix it. Or at least most of it

**Comment by CWKevo** [comment]
**Update:** I have now fixed hopefully everything for you. I had to delete all tags and re-create them, feel free to alter them to your liking. Permissions for them will need to be re-setup too, unfortunately I was unable to recover them due to how the data is saved in the database.

Also, I've created another backup of current working database. Let me know if you encounter any more issues by replying to this thread.
