### ISSUE TITLE
Only Third party login.

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#249]
__Packagist URL for extension:__
https://packagist.org/packages/v17development/flarum-third-party-login-only

Disscus; https://discuss.flarum.org/d/28424-third-party-login-only-block-standard-login

__Why should we install the extension?__

Block the main login to encourage users to use third party logins. An alternative way to prevent spammers or unwanteds hackers to join the forum.

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
I've removed the extension because it was not being used by many forums. Some forums mistakenly thought that this extension added third party login, which crashed their forum when OAuth wasn't enabled too.

If enough people are interested in having this extension back, reply to this thread and I will reopen this issue
