### ISSUE TITLE
Max characters extender

### ISSUE THREAD

**Issue by mauro334** [gwillem/freeflarum.com#268]
Topic : https://flarum.it/d/176-numero-massimo-caratteri-di-un-post

__Why should we install the extension?__
To increase max characters limit for single post from 65535 _to infinity and beyond_

**Comment by justoverclockl** [comment]
there's no extension at moment but if freeflarum need an extension for that, i can create this for the benefit of freeflarum community.

**Comment by CWKevo** [comment]
A few things:
1. That is not an English post, nor an extension. It requires manual extenders and file editing (AFAIK). That is not available for FreeFlarum users, since we do not provide that functionality and don't plan to.
2. Why would you need to have a post longer than 65535 characters anyways? I think that a post never has to go longer than that - at that point you can just create another post below the original one.

Thanks for the efforts @justoverclockl. However, I am not so sure about this

**Comment by mauro334** [comment]
Actually, trying to count the characters it came out that the post was only 3020 thousand long. Now I understand why you said that _a post never has to go longer than that_. I don't know why but I've tried to write more and it's working fine at the moment.

Thanks to @justoverclockl for his willingness and to @CWKevo for claryfing.

**Comment by CWKevo** [comment]
It's alright, I'm closing this for now. If you have any more concerns about this, please reply and reopen this issue
