### ISSUE TITLE
Evergreen, an reddit like extension.

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#269]
__Packagist URL for extension:__
https://packagist.org/packages/kyrne/evergreen

__Why should we install the extension?__

Make comments more like Reddit.

**Comment by CWKevo** [comment]
I like this extension too, however it requires `flarum/mentions` to be removed first. Because all FreeFlarum forums share the same extensions and need to stay synchronized, this is currently not possible. We'd have to remove mentions for all forums in order to install this extension for some forums that will use it.

I am leaving this open until it is possible for us to include it (e. g.: until compatibility with `flarum/mentions` is added)

**Comment by shawny43** [comment]
I see but there a little problem. There no developper post with Flarum/Mentions beacause is a core extension. Idk why.

**Comment by CWKevo** [comment]
If you look at Packagist, you can see that this extension has `flarum/mentions` in the "conflicts" section.

The way this works is that every developer can mark another package as incompatible with their package. This makes Composer refuse to install the extension, if that conflicting package is installed too. It doesn't matter if the extension is enabled or disabled.

Since all extensions are connected and synchronized across all forums, there is no way that we can install this extension without removing `flarum/mentions` first (AFAIK).

The developer stated that this extension uses an alternative mentions system, because the core one is not very extensive/compatible. I guess we'll wait until this gets sorted out first, but I don't think that we can include this extension anytime soon.

**Comment by CWKevo** [comment]
I am closing this for now, since it doesn't seem like we are able to include this anytime soon. Feel free to reopen this when it becomes compatible (or there is a way to include this extension).
