### ISSUE TITLE
Friends Of Flarum - Filter isn't working anymore for some reason.

### ISSUE THREAD

**Issue by shydert** [gwillem/freeflarum.com#272]
__Describe the bug:__

After the plugin updated, it won't work.

**To Reproduce:**

1. Post anything with a blacklisted word, then the plugin will not change the post to be under review.

**Expected behavior:**

If a post contains the blacklisted word, it should put the post under review, which isn't doing anymore after the update.

**Comment by shydert** [comment]
Yeah there is but I don't know how the logs work, so my forum name is Gab and the domain is loop.loopredesocial.ml.

**Comment by CWKevo** [comment]
I see nothing that is related to FoF Filter in your logs folder. There have been some reports in the past that had similar issues with FoF Filter not picking blocked phrases. I don't know what's wrong with it, because we don't have the tools to debug it or fix it.

Double check all settings and if you have permissions set up correctly (I am sure that admins and people with permissions bypass the filter).

You could post in the extension thread. If more info will be required, I could provide that too

**Comment by shydert** [comment]
It's okay! Also, I double checked and only admins can bypass the filter. I use an account to test the filter (which isn't an administrator) and it still won't work. Anyway, I made so that every post will need to be approved manually before being public as a protection. Probably it's some odd bug from the plugin, and developers are probably going to fix that soon.

**Comment by CWKevo** [comment]
Yeah, likely. Sorry for the inconveniences and that I couldn't help you much
