### ISSUE TITLE
Localization of FreeFlarum

### ISSUE THREAD

**Issue by jhhorch** [gwillem/freeflarum.com#280]
I would be very happy if they would translate the freeflarum interface into Hebrew as well

**Comment by CWKevo** [comment]
The implementation for localization is there, so it is possible. However, we do not speak Hebrew, so we need someone to do the translation for us.

There was once an idea to host FreeFlarum on rob006's Weblate instance, however I don't have the ability to assign permissions necessary for the bot to crawl the translations. I will later open an issue for this in our other repo, so that we can look into it soon. Perhaps you are interested to translate FreeFlarum to Hebrew?

**Comment by jhhorch** [comment]
The only language I know is Hebrew I do not speak any other languages

**Comment by jhhorch** [comment]
I want to start translating from English to Hebrew

**Comment by CWKevo** [comment]
At the moment, the folder with translations is bundled with FreeFlarum's source code, and it is not public. We will need to do some extra work first to make it open for people

**Comment by CWKevo** [comment]
Subrepo is now available at https://github.com/gwillem/freeflarum-i18n. Note that it is in an early state and things need to be cleaned up first. But I'm leaving the link here so you can take a look around and familiarize yourself with how the translations look like.

I will update the repository as soon as possible when I'll have the time, and then we might also put it on Weblate for easier translations
