### ISSUE TITLE
Support for OpenNIC

### ISSUE THREAD

**Issue by luqaska** [gwillem/freeflarum.com#298]
__What is OpenNIC?__
https://opennic.org/

__Why should this feature be added?__
I think this would make the experience of adding a cool domain for forums a much easier experience.

**Comment by CWKevo** [comment]
I am afraid that this will be very hard to set up and maintain. It would require us to completely modify our entire backend and setup. I'd say that this is suitable to individuals only rather than a service like FreeFlarum.

From what I saw, it seems like a cool system, but I feel like it will be just too much for FreeFlarum.

**Comment by luqaska** [comment]
Do you know another service that could support it?
