### ISSUE TITLE
 zequeen/acgembed-remastered

### ISSUE THREAD

**Issue by essesoul** [gwillem/freeflarum.com#312]
__Packagist URL for extension:__
https://extiverse.com/extension/zequeen/acgembed-remastered
__Why should we install the extension?__
Add acfun.cn and bilibili.com in mediaembed;remastered from LCinHK

**Comment by CWKevo** [comment]
Looking at the source, there is only one file that is modified (https://github.com/ZeQueen-X/ACGEmbed-remastered/blob/main/extend.php).

I am a bit resistant to add this, because the entire code is crammed inside `extend.php`, in seemingly non-standard way. This extension doesn't seem to have a discussion at https://discuss.flarum.org too, which means that it is not mature enough. Also, you didn't state why we should include this extension, instead you just blindly copied the extension's description.

**Comment by CWKevo** [comment]
I've included this now. I am not sure how it works since I don't see any new buttons in the post composer. We will determine whether or not to keep this extension based on the amount of forums that use it
