### ISSUE TITLE
Hashtag does not appear

### ISSUE THREAD

**Issue by Profi420** [gwillem/freeflarum.com#320]
__Describe the bug:__

The #Hashtags addon does not create a link to the search. The plugin was activated, cache was cleared and in the settings the forum was 'fixed'. Nevertheless, unfortunately, nothing happens.

**Comment by CWKevo** [comment]
It is because the extensions are installed only on the main forum, and then we use the `rsync` command to synchronize it with other forums. Even if the extension appears in the list, it is not actually fully included in your forum yet.

However, if you tell me your forum name, I'll sync it for you earlier (or you can "Fixup your forum" at https://freeflarum.com/settings/forum_settings)

**Comment by Profi420** [comment]
thanks! works now
