### ISSUE TITLE
ganuonglachanh/sonic

### ISSUE THREAD

**Issue by essesoul** [gwillem/freeflarum.com#333]
__Packagist URL for extension:__
https://extiverse.com/extension/ganuonglachanh/sonic

__Why should we install the extension?__

Allows to search by sonic

**Comment by CWKevo** [comment]
As with #311, this requires us to create the first index for all forums that have enabled this extension. Since Flarum uses PHP and FreeFlarum uses Python, these two languages do not really integrate well, which means that we can't listen to when this extension was enabled and run the command automatically, or at least not easily.

I am not saying that these extensions have zero chance of being added, but they'll be harder to include and maintain by us. To me, it seems that they're far better for forums in a self-hosted environment, rather than on a free hosting like FreeFlarum.

However, I will probably look into implementing Blomstra's search at least (so I'll close this for now), as it seems that this will be the only way to improve & index Flarum's search database for a while. Improvements to the search from Flarum's side are planned, but I am not aware of it's current state. I guess that with the increasing number of search extensions, Flarum might just let extension developers extend the search bar instead, rather than doing a huge core search bar recode themselves.
