### ISSUE TITLE
ganuonglachanh/flarum-ext-search

### ISSUE THREAD

**Issue by essesoul** [gwillem/freeflarum.com#335]
__Packagist URL for extension:__
https://extiverse.com/extension/ganuonglachanh/flarum-ext-search

__Why should we install the extension?__

Support search in Discussion Title

**Comment by CWKevo** [comment]
Are you requesting this because you want to be able to search discussion titles only?

Flarum `^1.0.0` already supports searching discussion title (https://discuss.flarum.org/d/6126/30), and the new behavior of the extension seems to be that it only enabled searching the title (https://discuss.flarum.org/d/6126/31). This is useful for forums with thousands of discussions, but since FreeFlarum doesn't officially support huge forums with many discussions, I see no benefits from including this extension.

**Comment by CWKevo** [comment]
Closing this for now, if anyone is interested in this then we can re-open it and include it
