### ISSUE TITLE
flarum-link-preview 

### ISSUE THREAD

**Issue by Profi420** [gwillem/freeflarum.com#341]
__Packagist URL for extension:__
https://packagist.org/packages/datlechin/flarum-link-preview

__Why should we install the extension?__
A [Flarum](http://flarum.org/) extension. Automatically display a rich preview of the link contents, such as title, description and image. This extension uses Google Favicon service to get the favicon and uses meta-grabber.herokuapp.com as a third-party to get site meta.

**Comment by CWKevo** [comment]
Unfortunately, we can't include this at the moment because this extension requires [spekulatius/phpscraper](https://packagist.org/packages/spekulatius/phpscraper):`^0.5.2`, which requires [symfony/dom-crawler](https://packagist.org/packages/symfony/dom-crawler):`^5.0`, but [katosdev/signature](https://packagist.org/packages/katosdev/signature) requires [symfony/dom-crawler](https://packagist.org/packages/symfony/dom-crawler):`^6.0.2`.

This means that in order to install this extension, we'd have to remove the Signature extension. Since `phpscraper` requires `dom-crawler:^5.0` and it's a third party package, we'd need to wait for the author to update to `dom-crawler:^6.0` (or `katosdev/signature` would have to downgrade the package, and I doubt that'll happen). I'm keeping this open for now

**Comment by CWKevo** [comment]
This can be installed now, so I've included it
