### ISSUE TITLE
Migrating Flarum to freeflarum

### ISSUE THREAD

**Issue by changfeng2021** [gwillem/freeflarum.com#356]
Hi
I already have a Flarum running and I want to migrate to freeflarum, can I import my own database
The version I am using is as follows:
Flarum -> 1.0.2
PHP -> 8.0.6
MySQL -> 10.5.13-MariaDB

**Comment by CWKevo** [comment]
Hello,

we are generally against the idea of importing an existing forum to FreeFlarum. We have created the project as a way for new communities to setup their forum and when they grow big enough, they can migrate away (not the other way around, like in your case).

However, we have made this feature available for donors that have donated 20 € or more. This is because importing an existing community means that you have already gotten some active userbase and content, which is not really ideal for a free service. Actually,I am thinking of suggesting to remove this feature completely in the future, since some people might mistaken it for a commercial service (which we aren't and will not be), to make things simpler.

**Quickedit:** This is now closed
