### ISSUE TITLE
Update to Flarum 0.1.0-beta

### ISSUE THREAD

**Issue by Gerryfw** [gwillem/freeflarum.com#39]
When is it foreseeable that the update will be available?

https://discuss.flarum.org/d/21349-flarum-0-1-0-beta-10-released

**Comment by xCustomWorld** [comment]
Hopefully very soon. I must admit I haven't even noticed that they have released beta.10 because I'm now busy with tons of other things and basically my "busy-o-ness" just started. I don't know if @gwillem shares the same, but keep in mind that a lot of extensions will need to be updated.

I suggest to just wait some time until most extensions will be updated. Let's just give developers (and us) time to sort things out and tidy everything they need :')

**Comment by gwillem** [comment]
In progress! Eta 3-4 hours for all forums to be running beta10.
