### ISSUE TITLE
Profile Cover

### ISSUE THREAD

**Issue by taciturasa** [gwillem/freeflarum.com#49]
__Packagist URL for extension:__
https://packagist.org/packages/sycho/flarum-profile-cover

__Why we should install this extension?__
- You should install it because it would allow for more social media-like profiles in a forum.
- I want this extension because I would like users to be able to be able to create cover photos.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
Listed as 0.10: https://flagrow.io/extensions/sycho/flarum-profile-cover

**Comment by xCustomWorld** [comment]
A small note: FreeFlarum does not allow anything that accepts custom file upload, **but** if the extension only allows uploading images (e.g. it has filter to upload only image files - trust me, many developers forget about these), I think that it's fine then. We block custom upload extensions because of viruses and PhP codes and other abuse, but there is even a 2MB limit for the cover photo (so people can't upload 2GB to fill out FreeFlarum's host space).

In my opinion, it is a clean extension, however I think that we should find a way around that and handle upload extensions better and with more control.

Simple extension. Notes above were for @gwillem (and possibly other people) as he is the owner of FreeFlarum. If we would block that extension, we can block profile photo upload too, as it's the same in the principe. 
+1 for this :+1:

**Comment by taciturasa** [comment]
Yeah, precursory glance it looks like it's image only.

**Comment by Gizmotronn** [comment]
Is there any update on this? The extension only allows for image upload...

**Comment by CWKevo** [comment]
I have added this extension, however it seemed to not provide any admin settings dialog, and didn't add option to upload the profile cover. I will look into it further, but for now, it seems to not work.
