### ISSUE TITLE
Japanese Language

### ISSUE THREAD

**Issue by Chrisflarum** [gwillem/freeflarum.com#60]
Can you please install the Japanese language.

Packagist URL for extension:
https://packagist.org/packages/rikusen0335/lang-japanese-extended

It would be fantastic to be able to use the flarum forum on our Japanese websites.

Thanks in advance.

**Comment by Chrisflarum** [comment]
https://discuss.flarum.org/d/20641-japanese-language-pack-extended

**Comment by gwillem** [comment]
Installed!

**Comment by Chrisflarum** [comment]
Hi, can you please check this again, as the Japanese language does not work. I have tried to install, but there are just random strings showing up and not Japanese.

**Comment by xCustomWorld** [comment]
Random strings in translations mean that the extension is not developed correctly/still outdated. I assume that by "random strings" you mean stuff like `core.ref.user` for example and other broken translations.

Sadly, we cannot assist you with this issue, because extensions aren't developed by us. You should ask the extension's author for a fix. Or you can have a look in the extension's code and build it by your own. I'm sorry that I couldn't help you, but maybe others can.
