### ISSUE TITLE
Follow Tags by FriendsOfFlarum

### ISSUE THREAD

**Issue by brechtm** [gwillem/freeflarum.com#64]
__Packagist URL for extension:__
https://packagist.org/packages/fof/follow-tags

__Why we should install this extension?__
You should install it because it seems very useful. I wanted to set up a forum for my community, but this missing feature is a deal-breaker, unfortunately.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

Extension was updated recently: https://discuss.flarum.org/d/20525-friendsofflarum-follow-tags/52

**Comment by xCustomWorld** [comment]
I think that this extension was requested earlier at Flarum's Discuss, unfortunately we cannot currently install this extension because it would generate a lot of mails.

Edit: No, it was not requested yet, but this is very related: https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com/936

I'm closing this for now. Sorry that we couldn't help you. If you want to notify your users of every new discussion, you can check my alternative solution about webhooks here: https://github.com/gwillem/freeflarum.com/issues/1
(and perhaps you can also ask the extension's developer for an ability to filter webhooks by tags. I know it's not exactly what you want, but I think that this is currently the closest solution to your problem).

**Comment by brechtm** [comment]
That's too bad, but entirely understandable.

I did see that it's possible to configure your own mail sending service. Would it be possible to make this extension available on the condition that the user configures his own mail sending service?

**Comment by xCustomWorld** [comment]
With some additional setup, yes. But I think that we would have to review every forum manually, because I think that we would have to modify those extension's code and this would be a tough job.

We could make it so that it requires custom mail setup to enable these extensions, but this would have to be worked on  too (I mean that we just have other priorities at the moment). 

In my opinion, it would be possible to just allow everyone to enable the extension, and if FreeFlarum found a forum that has not configured custom mail settings, FreeFlarum will take appropriate action. But this would be very dangerous.

I'm just listing a few possible ideas I could think of, please do not take them seriously as I'm still pretty sure that your requested feature wouldn't be possible in the near future, unfortunately. Good luck with your forum, hope you find any suitable alternative :')

**Comment by brechtm** [comment]
Thanks for the informative response. And the best of luck with the project!
