### ISSUE TITLE
White screen of death /Arabic language extension

### ISSUE THREAD

**Issue by Cyb01g** [gwillem/freeflarum.com#73]
**Describe the bug**
White screen of death. 
Warning!:
Completely unable to do anything, you won't be able to access your control panel after this.

I've deleted my forum after reaching this point.
xxx.freeflarum.com

1. Go to the control panel
2.  Install/Activate the Arabic language extension
3. Switch your default board language to Arabic
 

White screen of death. 

**Expected behavior**

White Death Screen.

White page.

**Comment by xCustomWorld** [comment]
The Arabic language pack errors & issues have been around for quite some time now. Unfortunately, we cannot fix this errors, as we do not develop extensions. Please, report this issue to extension's developer(s). If it doesn't get fixed, FF will just have to remove the extension.

As for these issues, you didn't have to remove your forum. FreeFlarum can always disable the extension on your forum, so that the error will disappear and you can then use your forum normally. 

Or you can always create second admin account in case you brick your original one like this. Then, you just switch your accounts and disable the problem extension.

**Comment by gwillem** [comment]
@Cyb01g thanks for reporting, currently the latest Arabic update is being installed, it should fix this issue.
