### ISSUE TITLE
Flarum Categories

### ISSUE THREAD

**Issue by Aid-12114** [gwillem/freeflarum.com#97]
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
https://packagist.org/packages/askvortsov/flarum-categories

__Why we should install this extension?__
You should install it because categories would be good instead of not being able to see which category each post should be in.

> ** We only honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote. **

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL 
![image](https://user-images.githubusercontent.com/66113140/83316311-ad34e200-a257-11ea-9086-e358fffc0a04.png)

https://forum.youthneuro.org/

**Comment by CWKevo** [comment]
I believe the tags extension already has similar features, did you check it? I assume it didn't meet your requirements, may I know what you want to achieve with this extension then (eg. why you choose this one over Tags)?

If you want it just because of the description (for others to see what belongs to what tag), the Tags extension already has this feature. I will write the documentation for the rest of the extensions soon now that I have time.

**Comment by Aid-12114** [comment]
The thing is, the Tag Extension functions weirdly...

![Screen Shot 2020-05-30 at 4 52 58 pm](https://user-images.githubusercontent.com/66113140/83324181-06236b00-a296-11ea-98e6-784ce06b966d.png)

Anyway to fix?

**Comment by CWKevo** [comment]
Glad you got it fixed! Other problems for the issue above are (in case others have [had] the same problem):
1. You have disabled the English language extension and the Tags extension isn't translated into the language your forum is using. Always keep English pack enabled, as the untranslated strings will be able to fallback to English ones.
2. You haven't cleared cache (this case).

We can leave this issue open in case others need/want it, but I think that the Tags extension is better at this (if properly configured, and with some tweaking).

**Comment by Bluejeanx** [comment]
This could be useful for some communities on the FreeFlarum platform. I gave it a thumbs up!

**Comment by CWKevo** [comment]
Just a small note that this extension seems more like a lower-priority one to me, because the Tags extension already has those (or similar) features - this extension is not needed, however it could act as a smaller version of Tags which purpose is just the categories part for communities that do not want a tags system.

This one has received 5 upvotes, which means that the chances of it being added are higher and higher :)

**Comment by allroundernaman** [comment]
Hey I am also looking for this feature for my forum. Kindly provide.
Regards,

**Comment by ririko5834** [comment]
I am looking for this extension, please add it 🙏

**Comment by NamVr** [comment]
Yes but i think tags extension will do the work, I use it now :)

**Comment by CWKevo** [comment]
Installed!
